- hosts: localhost
  connection: local
  tasks:
    - name: eOS01
      become: yes
      pacman:
        name: "{{ lookup('file', 'pkglist.txt').splitlines() }}"
        state: present
        update_cache: yes
        
    - name: Docker install
      become: yes
      pacman:
        name: 
          - docker
          - docker-compose
        state: present
  
    - name: Docker service enable
      become: yes
      systemd:
        name: docker
        enabled: yes
        state: started
